<?php

declare(strict_types=1);

use App\Core\Router;
use App\Controllers\AuthController;
use App\Controllers\AdminWorldEditorController;
use App\Controllers\ArtifactController;
use App\Controllers\BettingController;
use App\Controllers\BuildingController;
use App\Controllers\CivilizationController;
use App\Controllers\EventController;
use App\Controllers\ExportController;
use App\Controllers\HeroController;
use App\Controllers\HistoryController;
use App\Controllers\InfluenceController;
use App\Controllers\LandmarkController;
use App\Controllers\MagicDiscoveryController;
use App\Controllers\MythologyController;
use App\Controllers\PantheonController;
use App\Controllers\RegionController;
use App\Controllers\ResourceNodeController;
use App\Controllers\SettlementController;
use App\Controllers\StatisticsController;
use App\Controllers\StatusController;
use App\Controllers\TemporalOmenController;
use App\Controllers\WeatherController;
use App\Middleware\JwtAuthMiddleware;
use App\Middleware\AdminAuthMiddleware;

return function (Router $router): void {
    $api = '/api';
    $auth = [JwtAuthMiddleware::class];
    $admin = [JwtAuthMiddleware::class, AdminAuthMiddleware::class];

    $router->get($api . '/site-status', function ($request, $response) {
        $response->getBody()->write(json_encode(['status' => 'OK']));
        return $response->withHeader('Content-Type', 'application/json');
    });

    $router->get($api . '/auth/login-info', [AuthController::class, 'getLoginInfo']);
    $router->post($api . '/auth/guest-session', [AuthController::class, 'createGuestSession']);
    $router->get($api . '/public/chronicle-share/{shareId}', [ExportController::class, 'getPublicChronicleShare']);

    $router->get($api . '/auth/session', [AuthController::class, 'getCurrentUser'], $auth);
    $router->get($api . '/auth/me', [AuthController::class, 'getCurrentUser'], $auth);
    $router->put($api . '/auth/preferences', [AuthController::class, 'updatePreferences'], $auth);
    $router->post($api . '/auth/link-guest', [AuthController::class, 'linkGuestAccount'], $auth);

    $router->get($api . '/regions', [RegionController::class, 'getAllRegions'], $auth);
    $router->get($api . '/regions/{id}', [RegionController::class, 'getRegionById'], $auth);
    $router->get($api . '/regions/{id}/landmarks', [RegionController::class, 'getRegionLandmarks'], $auth);
    $router->post($api . '/regions', [RegionController::class, 'createRegion'], $admin);
    $router->post($api . '/regions/{id}/process', [RegionController::class, 'processRegionTick'], $admin);
    $router->get($api . '/champions', [HeroController::class, 'getChampionStatus'], $auth);
    $router->get($api . '/artifacts', [ArtifactController::class, 'getArtifacts'], $auth);
    $router->post($api . '/artifacts', [ArtifactController::class, 'createArtifact'], $auth);
    $router->post($api . '/artifacts/{id}/empower', [ArtifactController::class, 'empowerArtifact'], $auth);
    $router->post($api . '/artifacts/{id}/transfer', [ArtifactController::class, 'transferArtifact'], $auth);
    $router->post($api . '/artifacts/{id}/stabilize', [ArtifactController::class, 'stabilizeArtifact'], $auth);
    $router->get($api . '/weather', [WeatherController::class, 'getWeather'], $auth);
    $router->post($api . '/weather/nudge', [WeatherController::class, 'nudgeWeather'], $auth);
    $router->get($api . '/omens', [TemporalOmenController::class, 'getOmens'], $auth);
    $router->post($api . '/omens', [TemporalOmenController::class, 'readOmen'], $auth);
    $router->get($api . '/magic', [MagicDiscoveryController::class, 'getMagic'], $auth);
    $router->post($api . '/magic/research', [MagicDiscoveryController::class, 'researchMagic'], $auth);
    $router->get($api . '/myths', [MythologyController::class, 'getMyths'], $auth);
    $router->post($api . '/myths/promote', [MythologyController::class, 'promoteMyth'], $auth);
    $router->get($api . '/civilization', [CivilizationController::class, 'getCivilization'], $auth);
    $router->post($api . '/civilization/advance', [CivilizationController::class, 'advanceCivilization'], $auth);
    $router->get($api . '/pantheon', [PantheonController::class, 'getPantheon'], $auth);
    $router->post($api . '/pantheon/{id}/counterplay', [PantheonController::class, 'counterplay'], $auth);
    $router->get($api . '/heroes', [HeroController::class, 'getAllHeroes'], $auth);
    $router->get($api . '/heroes/{id}', [HeroController::class, 'getHeroById'], $auth);
    $router->post($api . '/heroes/{id}/champion', [HeroController::class, 'designateChampion'], $auth);
    $router->post($api . '/heroes/{id}/champion/cultivate', [HeroController::class, 'cultivateChampion'], $auth);
    $router->get($api . '/settlements', [SettlementController::class, 'getAllSettlements'], $auth);
    $router->get($api . '/settlements/{id}', [SettlementController::class, 'getSettlementById'], $auth);
    $router->get($api . '/settlements/{id}/buildings', [SettlementController::class, 'getSettlementBuildings'], $auth);
    $router->get($api . '/events', [EventController::class, 'getAllEvents'], $auth);
    $router->get($api . '/events/{id}', [EventController::class, 'getEventById'], $auth);
    $router->get($api . '/history/summary', [HistoryController::class, 'getSummary'], $auth);
    $router->get($api . '/buildings', [BuildingController::class, 'getAllBuildings'], $auth);
    $router->get($api . '/buildings/{id}', [BuildingController::class, 'getBuildingById'], $auth);
    $router->post($api . '/buildings', [BuildingController::class, 'createBuilding'], $admin);
    $router->put($api . '/buildings/{id}', [BuildingController::class, 'updateBuilding'], $admin);
    $router->delete($api . '/buildings/{id}', [BuildingController::class, 'deleteBuilding'], $admin);
    $router->get($api . '/landmarks', [LandmarkController::class, 'getAllLandmarks'], $auth);
    $router->get($api . '/landmarks/{id}', [LandmarkController::class, 'getLandmarkById'], $auth);
    $router->post($api . '/landmarks', [LandmarkController::class, 'createLandmark'], $admin);
    $router->put($api . '/landmarks/{id}', [LandmarkController::class, 'updateLandmark'], $admin);
    $router->delete($api . '/landmarks/{id}', [LandmarkController::class, 'deleteLandmark'], $admin);
    $router->post($api . '/landmarks/{id}/discover', [LandmarkController::class, 'discoverLandmark'], $admin);
    $router->get($api . '/resource-nodes', [ResourceNodeController::class, 'getAllResourceNodes'], $auth);
    $router->get($api . '/resource-nodes/{id}', [ResourceNodeController::class, 'getResourceNodeById'], $auth);
    $router->post($api . '/resource-nodes', [ResourceNodeController::class, 'createResourceNode'], $admin);
    $router->put($api . '/resource-nodes/{id}', [ResourceNodeController::class, 'updateResourceNode'], $admin);
    $router->delete($api . '/resource-nodes/{id}', [ResourceNodeController::class, 'deleteResourceNode'], $admin);
    $router->post($api . '/bets', [BettingController::class, 'placeDivineBet'], $auth);
    $router->get($api . '/bets', [BettingController::class, 'getAllDivineBets'], $auth);
    $router->get($api . '/bets/summary', [BettingController::class, 'getDivineBetSummary'], $auth);
    $router->get($api . '/bets/{id}', [BettingController::class, 'getDivineBetById'], $auth);
    $router->get($api . '/speculation-events', [BettingController::class, 'getSpeculationEvents'], $auth);
    $router->get($api . '/betting-odds', [BettingController::class, 'getBettingOdds'], $auth);
    $router->get($api . '/bet-types', [BettingController::class, 'getBetTypes'], $auth);
    $router->post($api . '/combo-bets', [BettingController::class, 'createComboBet'], $auth);
    $router->post($api . '/combo-bets/preview', [BettingController::class, 'previewComboBet'], $auth);
    $router->get($api . '/export/types', [ExportController::class, 'getExportTypes'], $auth);
    $router->get($api . '/export/full', [ExportController::class, 'exportFull'], $auth);
    $router->get($api . '/export/chronicle-share', [ExportController::class, 'exportChronicleShare'], $auth);
    $router->get($api . '/export/chronicle-share/public', [ExportController::class, 'listPublicChronicleShares'], $auth);
    $router->post($api . '/export/chronicle-share/public', [ExportController::class, 'publishChronicleShare'], $auth);
    $router->delete($api . '/export/chronicle-share/public/{shareId}', [ExportController::class, 'revokePublicChronicleShare'], $auth);
    $router->get($api . '/export/chronicle-replay', [ExportController::class, 'exportChronicleReplay'], $auth);
    $router->get($api . '/export/{type}', [ExportController::class, 'exportByType'], $auth);
    $router->post($api . '/influence/divine/calculate-cost', [InfluenceController::class, 'calculateDivineInfluenceCost'], $auth);
    $router->post($api . '/influence/divine/apply', [InfluenceController::class, 'applyDivineInfluence'], $auth);
    $router->post($api . '/influence/hero/empower', [InfluenceController::class, 'empowerHero'], $auth);
    $router->post($api . '/influence/hero/guide', [InfluenceController::class, 'guideHero'], $auth);
    $router->post($api . '/influence/region/guide-research', [InfluenceController::class, 'guideRegionResearch'], $auth);
    $router->post($api . '/influence/region/{id}', [InfluenceController::class, 'applyRegionInfluenceAction'], $auth);
    $router->post($api . '/influence/hero/{id}', [InfluenceController::class, 'applyHeroInfluenceAction'], $auth);
    $router->get($api . '/status', [StatusController::class, 'getGameStatus'], $auth);
    $router->post($api . '/admin/game-loop/tick', [StatusController::class, 'runGameTick'], $admin);
    $router->post($api . '/admin/game-loop/start', [StatusController::class, 'startGameLoop'], $admin);
    $router->post($api . '/admin/game-loop/stop', [StatusController::class, 'stopGameLoop'], $admin);
    $router->post($api . '/admin/era/transition', [StatusController::class, 'runEraTransition'], $admin);
    $router->get($api . '/admin/world-editor', [AdminWorldEditorController::class, 'getStatus'], $admin);
    $router->post($api . '/admin/world-editor/{entityType}/preview', [AdminWorldEditorController::class, 'previewEntity'], $admin);
    $router->post($api . '/admin/world-editor/{entityType}', [AdminWorldEditorController::class, 'createEntity'], $admin);
    $router->put($api . '/admin/world-editor/{entityType}/{id}', [AdminWorldEditorController::class, 'updateEntity'], $admin);
    $router->get($api . '/statistics/summary', [StatisticsController::class, 'getSummary'], $auth);
    $router->get($api . '/statistics/heroes', [StatisticsController::class, 'getHeroStats'], $auth);
    $router->get($api . '/statistics/regions', [StatisticsController::class, 'getRegionStats'], $auth);
    $router->get($api . '/statistics/financials', [StatisticsController::class, 'getFinancialStats'], $auth);
    $router->post($api . '/admin/process-expired-bets', [BettingController::class, 'processExpiredBets'], $admin);
};
